name: CI

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run golang-ci-lint
        uses: actions-contrib/golangcli-lint@v1